name: wiser_portfolio_optimization_env
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.7.15=haa95532_0
  - expat=2.7.1=h8ddb27b_0
  - libffi=3.4.4=hd77b12b_1
  - openssl=3.0.17=h35632f6_0
  - python=3.10.18=h981015d_0
  - sqlite=3.50.2=hda9a48d_1
  - tk=8.6.14=h5e9d12e_1
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py310haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.2.13=h8cc25b3_1
  - pip:
      - aiobotocore==2.23.2
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiohttp-cors==0.8.1
      - aioitertools==0.12.0
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.13.2
      - anyio==4.10.0
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.3.0
      - asttokens==3.0.0
      - async-lru==2.0.5
      - async-timeout==5.0.1
      - attrs==25.3.0
      - babel==2.17.0
      - backoff==2.2.1
      - beautifulsoup4==4.13.4
      - bleach==6.2.0
      - botocore==1.39.8
      - cachetools==5.5.2
      - certifi==2024.7.4
      - cffi==1.17.1
      - charset-normalizer==3.4.2
      - click==8.2.1
      - cloudpickle==2.2.1
      - colorama==0.4.6
      - colorful==0.5.7
      - comm==0.2.3
      - contourpy==1.3.2
      - cplex==22.1.2.0
      - cryptography==45.0.5
      - cycler==0.12.1
      - cython==3.1.2
      - debugpy==1.8.15
      - decorator==5.2.1
      - defusedxml==0.7.1
      - deprecated==1.2.18
      - dill==0.4.0
      - distlib==0.4.0
      - docplex==2.30.251
      - exceptiongroup==1.3.0
      - executing==2.2.0
      - fastjsonschema==2.21.1
      - filelock==3.18.0
      - fonttools==4.59.0
      - fqdn==1.5.1
      - frozenlist==1.7.0
      - fsspec==2025.7.0
      - google-api-core==2.25.1
      - google-auth==2.40.3
      - googleapis-common-protos==1.70.0
      - grpcio==1.74.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - ibm-cloud-sdk-core==3.24.2
      - ibm-platform-services==0.68.1
      - idna==3.10
      - importlib-metadata==8.4.0
      - ipykernel==6.30.0
      - ipython==8.37.0
      - ipywidgets==8.1.7
      - isoduration==20.11.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - jmespath==1.0.1
      - json5==0.12.0
      - jsonpointer==3.0.0
      - jsonschema==4.25.0
      - jsonschema-specifications==2025.4.1
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-core==5.8.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.2.6
      - jupyter-server==2.16.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.5
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.15
      - kiwisolver==1.4.8
      - lark==1.2.2
      - llvmlite==0.44.0
      - markupsafe==3.0.2
      - matplotlib==3.10.3
      - matplotlib-inline==0.1.7
      - mistune==3.1.3
      - mpmath==1.3.0
      - msgpack==1.1.1
      - mthree==3.0.0
      - multidict==6.6.3
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==2.8.5
      - notebook==7.4.5
      - notebook-shim==0.2.4
      - numba==0.61.2
      - numpy==2.2.6
      - opencensus==0.11.4
      - opencensus-context==0.1.3
      - openqasm3==1.0.1
      - opentelemetry-api==1.33.0
      - opentelemetry-exporter-otlp-proto-common==1.33.0
      - opentelemetry-exporter-otlp-proto-grpc==1.33.0
      - opentelemetry-exporter-prometheus==0.54b0
      - opentelemetry-instrumentation==0.54b0
      - opentelemetry-instrumentation-requests==0.54b0
      - opentelemetry-proto==1.33.0
      - opentelemetry-sdk==1.33.0
      - opentelemetry-semantic-conventions==0.54b0
      - opentelemetry-util-http==0.54b0
      - orjson==3.11.1
      - overrides==7.7.0
      - packaging==25.0
      - pandas==2.3.1
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pbr==6.1.1
      - pillow==11.3.0
      - pip==25.2
      - platformdirs==4.3.8
      - prometheus-client==0.22.1
      - prompt-toolkit==3.0.51
      - propcache==0.3.2
      - proto-plus==1.26.1
      - protobuf==5.29.5
      - psutil==7.0.0
      - pure-eval==0.2.3
      - py-spy==0.4.0
      - pyarrow==18.1.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycparser==2.22
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pygments==2.19.2
      - pyjwt==2.10.1
      - pylatexenc==2.10
      - pyparsing==3.2.3
      - pyspnego==0.11.2
      - python-dateutil==2.9.0.post0
      - python-json-logger==3.3.0
      - pytz==2025.2
      - pywin32==311
      - pywinpty==2.0.15
      - pyyaml==6.0.2
      - pyzmq==27.0.0
      - qiskit==2.1.1
      - qiskit-aer==0.17.1
      - qiskit-ibm-ai-local-transpiler==0.4.2
      - qiskit-ibm-catalog==0.9.0
      - qiskit-ibm-runtime==0.40.1
      - qiskit-ibm-transpiler==0.13.1
      - qiskit-qasm3-import==0.6.0
      - qiskit-serverless==0.25.3
      - ray==2.48.0
      - referencing==0.36.2
      - requests==2.32.4
      - requests-ntlm==1.3.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rpds-py==0.26.0
      - rsa==4.9.1
      - runningman==2.3.0
      - rustworkx==0.16.0
      - s3fs==2025.7.0
      - scipy==1.15.3
      - seaborn==0.13.2
      - send2trash==1.8.3
      - setuptools==57.4.0
      - six==1.17.0
      - smart-open==7.3.0.post1
      - sniffio==1.3.1
      - soupsieve==2.7
      - sspilib==0.3.1
      - stack-data==0.6.3
      - stevedore==5.4.1
      - symengine==0.13.0
      - sympy==1.14.0
      - terminado==0.18.1
      - tinycss2==1.4.0
      - tomli==2.2.1
      - tornado==6.5.1
      - tqdm==4.67.1
      - traitlets==5.14.3
      - types-python-dateutil==2.9.0.20250809
      - typing-extensions==4.14.1
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - uri-template==1.3.0
      - urllib3==2.5.0
      - uv==0.8.8
      - virtualenv==20.32.0
      - wcwidth==0.2.13
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - widgetsnbextension==4.0.14
      - wrapt==1.17.2
      - yarl==1.20.1
      - zipp==3.19.1

